"""Coarse destination-region map (IATA airport code -> region). Unknown codes -> 'OTHER'."""

_REGIONS = {
    "CN_MAINLAND": "PVG PEK PKX SHA HGH TFU NKG CKG HAK CSX WUH XIY KMG CGO XMN FOC TAO TSN DLC SYX CTU NGB TNA HRB SHE "
                   "CAN SZX KWL NNG WNZ HFE TYN URC LHW HET JJN LYG YNT SJW KWE ZUH LJG JZH SWA JHG NAY DYG",
    "TAIWAN": "TPE KHH RMQ TSA TNN",
    "JAPAN": "NRT HND KIX FUK NGO CTS OKA KOJ KMJ SDJ HIJ TAK KIJ OKJ KMQ FSZ ASJ ISG",
    "KOREA": "ICN GMP PUS CJU TAE",
    "SE_ASIA": "BKK MNL SIN KUL SGN DAD HAN CGK DPS CEB HKT CNX PEN RGN PNH REP KBV VTE DMK BKI KCH DVO ILO KLO SUB "
               "USM CRK KOS BWN VDH JHB LGK",
    "SOUTH_ASIA": "DEL BOM MAA BLR HYD CCU CMB DAC KTM MLE COK AMD",
    "OCEANIA": "SYD MEL BNE PER AKL ADL CHC CNS NAN GUM SPN",
    "EUROPE": "LHR LGW MAN CDG AMS FRA MUC ZRH FCO MXP MAD BCN VIE HEL IST DUB CPH ARN OSL BRU LIS ATH BUD PRG WAW",
    "N_AMERICA": "LAX SFO YVR YYZ JFK EWR ORD SEA BOS DFW IAD YUL SAN",
    "MIDDLE_EAST": "DXB DOH AUH RUH JED BAH KWI TLV",
    "AFRICA": "JNB ADD CAI NBO",
    "CENTRAL_ASIA": "TAS ALA",
    "RUSSIA": "SVO LED VVO",
}
IATA_TO_REGION = {code: region for region, codes in _REGIONS.items() for code in codes.split()}


def region_of(iata: str | None) -> str:
    return IATA_TO_REGION.get((iata or "").split(",")[0].strip(), "OTHER")
