[server]
headless = true
runOnSave = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#0b1220"
secondaryBackgroundColor = "#121c2e"
textColor = "#e6ebf2"
font = "sans serif"
